name: Build

on: [push, pull_request]

jobs:
  build-module:
    name: Build modules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - uses: actions/upload-artifact@v3
        with:
          name: magisk-module
          path: .
