name: Build

on: [push, pull_request]

jobs:
  build-module:
    name: Build modules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/upload-artifact@v4
        with:
          name: magisk-module
          path: .
